#!/usr/bin/dh-exec
[amd64] ../build/release_install/usr/bin/python3.bolt => usr/bin/python3.8-pyston2.3
[!amd64] ../build/release_install/usr/bin/python3 => usr/bin/python3.8-pyston2.3
../build/release_install/usr/bin/pip3.8 => usr/bin/pip-pyston2.3

../build/release_install/usr/include usr/
../build/release_install/usr/lib usr

# don't install man pages they would overwrite the normal cpython one
#build/opt_install/usr/share usr/
